Initial creation of repo
portway/portway pull request #1
Opened 2019-02-01 01:08 UTC by jcontonio

* Adds basic web and api services with docker-compose
* Adds basic express setup to both services
* Read the README on how to get moving
* Added prettier config and ran it
* Changed all the boilerplate Express Generator stuff to ES6 imports

## New

* Adds React, Webpack, and hot reloading broken out for each EJS view

2019-02-01 20:07 UTC, jjidt submitted a review, later dismissed
this looks like a good start, just the one comment on the commented out code

2019-02-01 20:07 UTC, jjidt commented on docker-compose.yml
> +# version: '3.4'
do we need this commented out code?

2019-02-02 02:07 UTC, jcontonio commented
This should be good to go now. I've added documentation as to what's going on with Express and Webpack on the web client. You can do local development now with hot reloading, and you can do a production build and start express, getting the hashed webpack bundles.

2019-02-02 22:45 UTC, jcontonio commented
Now have webpack configs split up per environment, a simple registration view, and Nodemon / Webpack behaving nicely with each other. Should be a good start.

2019-02-04 16:38 UTC, dheniges requested changes
Nice job wrangling this all together. There's a lot of things to think about starting a new app, thus the deluge of comments. Happy to help out on any of the requested updates.

2019-02-04 16:38 UTC, dheniges commented on .gitignore
> +
Needs `.DS_Store` added, looks like a couple of those files got committed

2019-02-04 16:38 UTC, dheniges commented on web/package.json
> +    "morgan": "~1.9.0",
there's a few libs in here that may be premature, like the cookie-parser, http-errors, and morgan. Did you copy this config from somewhere or purposefully add these libs?

2019-02-04 16:38 UTC, dheniges commented on web/package.json
> +    "node-sass-middleware": "0.11.0",
node-sass should presumably be a dev dependency. The prod build will want to do the sass builds and make sure those compiled css files are in the right public directory

2019-02-04 16:38 UTC, dheniges commented on web/package.json
> +    "webpack-assets-manifest": "^3.1.1"
this should also be a dev dependency.

A note on differentiating devDependency vs dependency: they are poorly named as the app still requires some of the devDependencies to build before it's run in prod. Dependencies should be the minimal set of libs required to run the production app _after it's built_. `npm install --production` installs everything in `dependencies`, so that's how we get the prod dependencies and nothing else installed.

2019-02-04 16:38 UTC, dheniges commented on web/src/app.js
> +import sassMiddleware from 'node-sass-middleware'
these dependencies won't be available in production, so they can't be imported. I don't remember if the import syntax supports conditional imports or if we'll need to do something else to handle that

2019-02-04 16:38 UTC, dheniges commented on web/src/libs/express-utilities.js
> +    // named pipe
I'm guessing this is copied code from somewhere? The web server is only going to be handling http connections, not named pipes, so this should throw an error to let us know the requested PORT is not a number to make config validation/debug easier

2019-02-04 16:38 UTC, dheniges commented on web/webpack.config.js
> +const devMode = process.env.NODE_ENV !== 'production'
We're going to want to break out this webpack config into either 2 files, or import config for the requested environment. The problem with the ternary expressions sprinkled throughout the file is what happens when you want to add a 3rd environment? Our local dev config may be different from a kubernetes dev environment which may be different than a CI environment etc. etc.

This can be done later.

2019-02-04 16:41 UTC, dheniges commented on web/webpack.config.js
> +const devMode = process.env.NODE_ENV !== 'production'
Apparently I didn't review the very latest, as you already broke out the webpack config into two files 👏   I just browsed through the files again and looks like everything else is set, not sure how I didn't have the latest on the webpack config files

2019-02-04 20:55 UTC, dheniges approved these changes

2019-02-04 20:57 UTC, merged