UI field ordering to endpoint and reducer
portway/portway pull request #108
Opened 2019-04-24 22:18 UTC by jcontonio

* Adds field order action / reducer
* Hits endpoint to re-order a field

This works, but I'm mutating state in the reducer and don't necessarily know the best way to not do that 🤷‍♂️

2019-04-26 16:33 UTC, jcontonio commented on web/src/client/js/reducers/documentFields.js
> +      if (oldOrder === newOrder) return state
I have this in the component, do you think it's worth removing from there so that at least the action triggers?

2019-04-26 16:35 UTC, jjidt commented on web/src/client/js/reducers/documentFields.js
> +      if (oldOrder === newOrder) return state
In this case, I think it can be in both places

2019-04-26 16:36 UTC, jcontonio commented on web/src/client/js/reducers/documentFields.js
> +      const { [fieldId]: fieldToUpdate, ...remainingFields } = documentFields
Oh this is nice to get the field and remaining fields... very nice

2019-04-29 17:08 UTC, dheniges requested changes
Looks like a leftover util function that can maybe be removed

2019-04-29 17:08 UTC, dheniges commented on web/src/client/js/reducers/documentFields.js
> +import { filterObject } from 'Shared/utilities'
Looks like this isn't used?

2019-04-29 17:08 UTC, dheniges commented on web/src/shared/utilities.js
> +export const filterObject = (obj, predicate) => {
Remove this function? Or document it (looks like it takes a function as a second arg that's supposed to return a boolean when given the value of an object's key?)

2019-04-29 17:30 UTC, jjidt commented on web/src/client/js/reducers/documentFields.js
> +import { filterObject } from 'Shared/utilities'
yeah, I was on the fence on that one, since it's maybe a useful util

YAGNI though, we can add it when it's used

2019-04-30 15:04 UTC, dheniges approved these changes

2019-04-30 16:29 UTC, merged