publish coordinator
portway/portway pull request #115
Opened 2019-05-02 21:29 UTC by dheniges

- It versions a document and copies all its fields and values
- Coordinator tests are integration because I was concerned I was just making up stuff and the publish wasn't actually happening 🤷‍♂  I can add unit tests as well if that sounds useful
- DocumentVersion gets Business-y

2019-05-03 20:29 UTC, jjidt requested changes
I like the integration tests here, and I don't think we need unit tests as long as we have these  💯 

just a couple small changes

2019-05-03 20:29 UTC, jjidt commented on api/src/businesstime/documentversion.test-i.js
> +    it('should have a verison number', () => {
typo

2019-05-03 20:29 UTC, jjidt commented on api/src/coordinators/documentVersion.js
> +  const doc = await BusinessDocument.findByIdForProject(docId, projectId, orgId)
do we need a check here that the document exists and a 404 if not? might be coming back null

2019-05-03 20:29 UTC, jjidt commented on api/src/coordinators/documentVersion.js
> +  const doc = await BusinessDocument.findByIdForProject(docId, projectId, orgId)
probably a test for that situation too

2019-05-06 19:12 UTC, dheniges commented
@jjidt updated

2019-05-06 20:01 UTC, jjidt approved these changes

2019-05-06 20:05 UTC, merged