Publish endpoint + queries
portway/portway pull request #125
Opened 2019-05-08 17:39 UTC by dheniges

- Adds ability to add `?draft=true` flag to `/documents/:id` and `/documents/:id/fields` to get draft fields. Otherwise endpoints return most recent published fields.
- Adds publish endpoint

- Field ordering needs to be updated to handle published/non-published fields
- UI updates needed

2019-05-09 01:23 UTC, jjidt requested changes
Tests look great! really cool to see all of this coming together

Seems like field updating might not be working yet. If I publish a version, go back and change a field value, and publish again the field isn't updated in the published field return

2019-05-09 01:23 UTC, jjidt commented on api/src/businesstime/field.test-i.js
> +          expect(Boolean(field.value)).toBe(true)
might be more explicit with `expect(field.value).toBeDefined())` instead?

2019-05-09 01:23 UTC, jjidt commented on api/src/db/__testSetup__/factories/document.js
> +    // console.info(projectData)
leftover ?

2019-05-09 16:43 UTC, jjidt commented
or is that field update covered in this ticket?

`Update /fields/:id endpoint to prevent deleting or editing a published field`

2019-05-13 18:13 UTC, dheniges commented
@jjidt ready for another peek. Re: update, if you update or add a field, the next publish should correctly grab that field/update. I manually tested both those scenarios and they worked as expected. I looked into testing it but it's sort of more an endpoint-level integration test.

2019-05-15 00:57 UTC, jjidt approved these changes
ah, I was previously testing with the UI which must not be updated to get the draft fields, so it was probably updating the published fields. Tested it with Postman and it looks good 👍

2019-05-15 03:09 UTC, dheniges commented
oh yeah, did I mention this is all API side so far? :D

2019-05-15 03:09 UTC, merged