UI – Form validation
portway/portway pull request #136
Opened 2019-05-14 22:12 UTC by jcontonio

Form validation

* Adds a Container with settings (resource, and field name) for when you don't want to connect to redux and pass errors down a chain... instead plop in `<ValidationContainer resource="project" value="name" />` to validate the project name anywhere in the app
* Adds a Component to use if you'd like to have more control, like say in the `TextField` and `CheckboxField` components. This way, you can pass errors down to form items and have the whole field change when there's an error

Other things:

* Adds a new ROUTE_CHANGE action when a route changes (using to clear validation state here)
* Fixes the bug when creating a new document, it'd fetch the API for `document/new`

**To test in UI**

1. Go to Project New and Project Settings
2. Inspect element, and remove the `disabled` property from submit buttons
3. Submit forms with empty values

2019-05-16 15:40 UTC, dheniges requested changes
Some small change requests

2019-05-16 15:40 UTC, dheniges commented on web/src/client/js/api/index.js
> +    const { data: { data }, status } = await axiosInstance.post(resource, body)
lol dataception going on here

2019-05-16 15:40 UTC, dheniges commented on web/src/client/js/api/index.js
> +    return {} // keep this here
having a "why" is helpful on these kinds of comments

2019-05-16 15:40 UTC, dheniges commented on web/src/client/js/components/Document/DocumentContainer.js
> +  if (typeof match.params.documentId === 'undefined' || match.params.documentId === 'new') {
should use the lovely `PATH_DOCUMENT_NEW_PARAM` constant instead of `new`

2019-05-16 15:40 UTC, dheniges commented on web/src/client/js/components/DocumentsList/DocumentsListContainer.js
> +      history.push({ pathname: `${Constants.PATH_PROJECT}/${match.params.projectId}/document/new` })
there's the constant `PATH_DOCUMENT_NEW` for this

2019-05-16 15:40 UTC, dheniges commented on web/src/client/js/components/DocumentsList/DocumentsListContainer.js
> +      creating={ui.documents.creating || match.params.documentId === 'new'}
again `PATH_DOCUMENT_NEW_PARAM` constant

2019-05-16 15:49 UTC, jcontonio commented on web/src/client/js/api/index.js
> +    const { data: { data }, status } = await axiosInstance.post(resource, body)
This is pure @jjidt madness

2019-05-17 14:46 UTC, dheniges approved these changes

2019-05-17 16:14 UTC, merged