UI Publish + Lockdown Published Fields
portway/portway pull request #141
Opened 2019-05-17 16:06 UTC by dheniges

- Prevents deleting published fields
- Prevents updating published fields
- Plugs in UI publish button to publish endpoint
- Fixes an ordering bug with publish

2019-05-17 17:34 UTC, dheniges commented
@jjidt ready for review whenever you get time today

2019-05-17 18:04 UTC, jjidt requested changes
Fun to see this working, everything looking good, just a couple specific test value checks

2019-05-17 18:04 UTC, jjidt commented on api/src/businesstime/field.test-i.js
> +        ).rejects.toThrow()
we should probably check the error code here

.rejects.toEqual(expect.objectContaining({ code: 403 }))

2019-05-17 18:04 UTC, jjidt commented on api/src/businesstime/field.test-i.js
> +        ).rejects.toThrow()
same

2019-05-20 16:21 UTC, jjidt approved these changes
nice 👍

2019-05-20 17:41 UTC, merged