UI – Users listing/creation
portway/portway pull request #153
Opened 2019-05-24 23:48 UTC by jcontonio

* Adds new Table component that is flexible grid instead of <table> (for future responsiveness)
* Adds user listing
* Adds user creation
* Adds user deletion

@jjidt can you see why the list isn't being updated after the the ADMIN update action? Also, User's emails are being set to their names, and I can't catch what's going on

2019-05-24 23:51 UTC, jcontonio commented
Looks like the name/email thing is API side

<img width="881" alt="image" src="https://user-images.githubusercontent.com/2809/58361512-2c712800-7e44-11e9-9a93-b0468eff2488.png">

2019-05-28 22:22 UTC, jjidt requested changes
getting a couple console errors in the client:

`Failed prop type: The prop `action.callback` is marked as required in `ToolbarComponent`, but its value is `undefined``

`Failed prop type: The prop `action.title` is marked as required in `ToolbarComponent`, but its value is `undefined``

2019-05-28 22:28 UTC, jjidt requested changes

2019-05-28 22:28 UTC, jjidt commented on web/src/client/js/components/Toolbar/ToolbarComponent.js
> +          {action.icon && (action.icon)}
duplicate ?

2019-05-28 22:28 UTC, jjidt commented on web/src/client/js/actions/user.js
> +      dispatch(Users.receiveOneUpdated(data))
This won't work how we want. The orgRole endpoint will return a 204 on success with no data, so we'll need a specific action for updating the user role, and we'll need to set the new role on the existing user in the User reducer.

2019-05-29 18:54 UTC, jjidt requested changes
Just a couple things,

Also, we probably don't want to allow users to delete themselves in the admin list, I tried it and everything (understandably) broke

2019-05-29 18:54 UTC, jjidt commented on web/src/client/js/actions/index.js
> +  RECEIVE_UPDATED_ROLE: 'RECEIVE_UPDATED_ROLE',
sorry, nitpicky, but can you make this RECEIVE_UPDATED_USER_ROLE to avoid the possibility of a namespace issue down the road

2019-05-29 18:54 UTC, jjidt commented on web/src/client/js/reducers/users.js
> +      //userObj.orgRoleId = orgRoleId
leftover

2019-05-29 21:03 UTC, jjidt approved these changes
🌮

2019-05-29 21:03 UTC, merged