organization billing
portway/portway pull request #174
Opened 2019-06-11 01:00 UTC by jjidt

2019-07-02 15:32 UTC, dheniges requested changes
Overall looking good code-wise. But how do I manually test this to create the stripe billing stuffs?

2019-07-02 15:32 UTC, dheniges commented on api/src/constants/billingPublicFields.js
> +  //address_line1_check,
are commented fields what's available to us? If so, maybe add a comment at the top of this constant?

2019-07-02 15:32 UTC, dheniges commented on api/src/controllers/orgBilling.js
> +    getOrgBilling
There are no permissions on `getOrgBilling`?

2019-07-02 15:32 UTC, dheniges commented on api/src/coordinators/billing.js
> +  if (!org.stripeId) return null
This is returning nothing in the body. Probably want an empty data object at minimum?

2019-07-02 17:01 UTC, dheniges commented
Also, when trying to update billing on the seed bonkey org I get this error:
```
danger-api | Error: No such token: tok_1ErpIbDBs6sqEFggtXQas4OV
danger-api |     at Constructor._Error (/api/node_modules/stripe/lib/Error.js:12:17)
danger-api |     at Constructor (/api/node_modules/stripe/lib/utils.js:134:13)
danger-api |     at new Constructor (/api/node_modules/stripe/lib/utils.js:134:13)
danger-api |     at Function.StripeError.generate (/api/node_modules/stripe/lib/Error.js:57:12)
danger-api |     at IncomingMessage.<anonymous> (/api/node_modules/stripe/lib/StripeResource.js:162:39)
danger-api |     at IncomingMessage.emit (events.js:194:15)
danger-api |     at IncomingMessage.EventEmitter.emit (domain.js:441:20)
danger-api |     at endReadableNT (_stream_readable.js:1103:12)
danger-api |     at process._tickCallback (internal/process/next_tick.js:63:19)
danger-api | PUT /api/organizations/100000/billing 500 288.228 ms - 1998
```

and FYI I reseeded dev to get the updated migrations

2019-07-02 17:58 UTC, jjidt commented
I think the api .env stripe secret has to be from the same account as the publicly viewable key we're using client-side in the StripeContainer

try it again with my creds and see if it works, or grab the `pk_test` key for your account and replace it in StripeContainer

2019-07-02 22:50 UTC, jjidt commented
@dheniges updated with a handful of changes

2019-07-03 15:22 UTC, dheniges requested changes
One sneaky console log. I was able to get it to work with your creds, looks good now 👍

2019-07-03 15:22 UTC, dheniges commented on api/src/controllers/orgBilling.js
> +  console.log(orgId, req.requestorInfo.orgId)
:eyes:

2019-07-03 16:05 UTC, jjidt commented on api/src/controllers/orgBilling.js
> +  console.log(orgId, req.requestorInfo.orgId)
oops, removed

2019-07-03 16:06 UTC, dheniges approved these changes

2019-07-03 16:10 UTC, merged