plans/seats
portway/portway pull request #248
Opened 2019-10-18 21:37 UTC by jjidt

@jcontonio the current subscription seat count will be available in the client on subscription.currentSeats

2019-10-22 15:14 UTC, dheniges requested changes
See my comments on the subscription re: "plan v. seat" and "create v. update". My hunch is we can break things down a bit to make it simpler to follow and update in the future.

2019-10-22 15:14 UTC, dheniges commented on api/src/coordinators/billing.js
> +  }
This if/else block concerns me a bit, as there are lots of cases being handled based on a combination of loosely coupled variables. The API endpoint seems reasonable at first glance (takes a `seats` number and a `planId`), but the combination of business logic between plans and seats and handling that in this `if/else` block is dense. The test coverage looks good though. Looking at the code, I wonder if we should separate out create vs. update, as both here and the stripe integrator are pulling out create vs. update and running separate logic. Potentially, this could be a `createOrUpdate` function since they both return a subscription, and then immediately branch off to a create coordinator function and an update coordinator function. Same for the stripe integrator. What do you think?

2019-10-22 15:14 UTC, dheniges commented on web/src/client/js/components/Admin/AdminPayment/AdminPaymentComponent.js
> +  return subscription.flatCost || '000'
Is this covering the scenario where flatCost may be undefined because the user is on a trial? I think it's worth a code comment

2019-11-04 22:05 UTC, dheniges reviewed
Comment on commented tests, otherwise it looks excellent :+1:

2019-11-04 22:05 UTC, dheniges commented on api/src/coordinators/billing.test-u.js
> +    // describe('when trying to change seat count on a single user plan', () => {
you still want these two commented tests?

2019-11-05 01:50 UTC, jjidt commented
@dheniges think we're ready to merge this when you give it the go ahead

2019-11-05 03:28 UTC, dheniges approved these changes
:tada:

2019-11-05 16:23 UTC, merged