Adds remove account UI
portway/portway pull request #309
Opened 2019-12-03 01:52 UTC by jcontonio

* Adds Remove Account UI in Billing section
* Adds "confirmedText" as an option to the Confirm component forcing you to type something to continue
* Hits the cancel account endpoint

2019-12-03 18:55 UTC, jjidt requested changes
Cancellation works, just a couple things.

Also, we need to fix some things with the flow, right now a 'TRIALING' user can cancel their account and they get 'INACTIVE' status, but this just results in a billing message, and they can enter billing info and get 'ACTIVE' status, which shouldn't be possible.  We need to completely lock out 'INACTIVE' users from the API and give them an 'Account removed, please contact blah blah if this was an error' message of some kind.

I think we can go ahead and merge this as soon as it's approved and do that in another PR, I think it'll involve passing in a set of acceptable statuses to certain API routes

2019-12-03 18:55 UTC, jjidt commented on api/src/coordinators/billing.js
> +  console.log(customer.subscriptions.data[0])
remove

2019-12-03 18:55 UTC, jjidt commented on web/src/client/js/components/Admin/AdminBilling/AdminBillingContainer.js
> +          <li>You will be able to log in for the next X days to undo this account.</li>
do you want to update these 'x' values? it will be conditional on whether they are TRIALING/TRIALING_PENDING_ACTIVE in which case their account will be immediately canceled, otherwise we can use the subscription.currentPeriodEnd value for 'x'

2019-12-03 19:14 UTC, jcontonio commented on web/src/client/js/components/Admin/AdminBilling/AdminBillingContainer.js
> +          <li>You will be able to log in for the next X days to undo this account.</li>
Oh good point, I'll add that in

2019-12-03 20:46 UTC, jcontonio commented on web/src/client/js/components/Admin/AdminBilling/AdminBillingContainer.js
> +          <li>You will be able to log in for the next X days to undo this account.</li>
@jjidt solved all of this, thanks

2019-12-03 20:48 UTC, jcontonio commented
> Cancellation works, just a couple things.
> 
> Also, we need to fix some things with the flow, right now a 'TRIALING' user can cancel their account and they get 'INACTIVE' status, but this just results in a billing message, and they can enter billing info and get 'ACTIVE' status, which shouldn't be possible. We need to completely lock out 'INACTIVE' users from the API and give them an 'Account removed, please contact blah blah if this was an error' message of some kind.
> 
> I think we can go ahead and merge this as soon as it's approved and do that in another PR, I think it'll involve passing in a set of acceptable statuses to certain API routes

I've broken out Notices and Cancel into their own components, and I am taking care of the case of a TRIALING user canceling, then adding payment. They can no longer do that (at least in the UI).

2019-12-04 01:06 UTC, jjidt approved these changes
👍 This looks good, I went ahead and pushed up a fix for the incorrect date thing, where it now forces a refetch of the billing info on cancel, and uses the currentPeriodEnd as a temporary stand-in

Still some things with the subscription flow that we need to touch up, let's go through that together sometime this week

2019-12-04 01:26 UTC, jcontonio commented
Sweet, thanks JJ! Yeah let’s do that

2019-12-04 01:27 UTC, merged