Free Account Setup
portway/portway pull request #314
Opened 2019-12-05 23:42 UTC by dheniges

- New admin route for creating a free multi user plan org
- New stripe subscription plans for free tiers
- Updates web to not show payment info on free plans, and message about contacting us to upgrade
- Example payload in the controller
- Secured by secret admin key
- Can invite > default number of users (currently 5), but cannot later add more in UI
- Free accounts can invite up to 5 users if not added via endpoint
- Adds free single user plan but no way to create an org with that currently, can add later

2019-12-06 20:19 UTC, jjidt requested changes
Works great, just a couple things

Also, wondering if we should put this at /admin/ instead of /api/admin/ then we could avoid the loader altogether and never accidentally mess with any admin routes? thoughts?

2019-12-06 20:19 UTC, jjidt commented on api/src/coordinators/demoSignup.js
> +        orgRoleId: user.role,
seems like we could end up with multiple users with the OWNER role who aren't necessarily referenced by the ownerId on the org.  So might want to iterate over the passed in users and ensure there's only one owner

2019-12-06 20:19 UTC, jjidt commented on web/src/client/js/components/Admin/AdminBilling/AdminBillingComponent.js
> +      <OrgPlanPermission acceptedPlans={[PLAN_TYPES.SINGLE_USER, PLAN_TYPES.MULTI_USER]}>
This keeps us from upgrading our seed user bonkey@bong.com, do we give them a plan: SINGLE_USER in the seed data? not sure what effects that will have if they don't have the matching stripe subscription

2019-12-06 21:17 UTC, dheniges commented on web/src/client/js/components/Admin/AdminBilling/AdminBillingComponent.js
> +      <OrgPlanPermission acceptedPlans={[PLAN_TYPES.SINGLE_USER, PLAN_TYPES.MULTI_USER]}>
I've been thinking about our seed data, I'm not sure how useful it is and will be going forward due to the reliance on stripe. If we want to test a lot of projects/documents/fields we have these beautiful APIs that makes that pretty easy to generate. We can always test signing up for a new account and org locally with the existing app code, and maybe in the future we add another admin route that would auto-verify the seed user? For the very moment I guess I will allow `null` as an acceptedPlan

2019-12-07 00:21 UTC, dheniges commented on api/src/coordinators/demoSignup.js
> +        orgRoleId: user.role,
added validation for that now

2019-12-07 00:21 UTC, dheniges commented on web/src/client/js/components/Admin/AdminBilling/AdminBillingComponent.js
> +      <OrgPlanPermission acceptedPlans={[PLAN_TYPES.SINGLE_USER, PLAN_TYPES.MULTI_USER]}>
added `null` support and tested with seed data

2019-12-07 00:22 UTC, dheniges commented
I moved the admin controller to `/admin` and outside the loader, agree it might be easy to do something we don't mean to do in there otherwise

2019-12-07 00:59 UTC, jjidt requested changes

2019-12-07 00:59 UTC, jjidt commented on api/src/coordinators/demoSignup.js
> +    ownerId: owner.id,
caught one other thing here, it looks like this is pulling the id from the passed in user object and not from the saved db user, so the ownerId isn't getting set

2019-12-07 01:24 UTC, jjidt approved these changes
🎉 🌮

2019-12-07 01:25 UTC, merged