businesstime!
portway/portway pull request #33
Opened 2019-03-12 00:36 UTC by jjidt

- moves user and project fetching/creation to businesstime layer
- moves user password functions to coordinator layer since this is touching the user model and also accessing the password generator/validator
- adds ono library for Error creation, which allows us to easily set error.code property anywhere in code, and then send that status to the api consumer.  Also allows us to re-throw errors with updated messages/data without losing stack trace
- All data coming out of BusinessTime :tm: are now POJOs

2019-03-12 15:26 UTC, dheniges requested changes
It all makes sense to me. I think you left an extraneous error in there, plus one naming nitpick

2019-03-12 15:26 UTC, dheniges commented on api/src/controllers/projects.js
> +    throw new Error('blarp')
v. informative

2019-03-12 15:26 UTC, dheniges commented on api/src/coordinators/user.js
> +import userBusiness from '../businesstime/user'
I think we should stick with either businessUser or userBusiness. In the projects controller you have businessProject

2019-03-12 16:19 UTC, jjidt commented on api/src/controllers/projects.js
> +    throw new Error('blarp')
haha

2019-03-12 23:37 UTC, dheniges commented on api/src/controllers/projects.js
> +    throw new Error('blarp')
blarp is still here?

2019-03-13 01:21 UTC, jjidt commented on api/src/controllers/projects.js
> +    throw new Error('blarp')
haha blarp forever

2019-03-13 15:14 UTC, dheniges submitted a review, later dismissed
Blarp is dead, long live Blarp! 👍

2019-03-13 15:56 UTC, jjidt commented
@dheniges realized I forgot status codes and error condition tests, added those if you wanna take a quick glance at that latest commit

2019-03-13 15:59 UTC, dheniges approved these changes
Updated tests still pass 👍

2019-03-13 16:00 UTC, merged