reset password
portway/portway pull request #403
Opened 2020-01-08 19:38 UTC by jjidt

2020-01-08 20:22 UTC, dheniges requested changes
I'm getting a compile error in web:
```
ERROR in multi ./src/client/css/index.scss ./src/client/js/passwordReset.js webpack-hot-middleware/client?path=/__webpack_hmr&timeout=20000&name=passwordReset
portway-web | Module not found: Error: Can't resolve './src/client/js/passwordReset.js' in '/web'
```

2020-01-08 23:39 UTC, dheniges requested changes
It works, but two things to either update or backlog:
- If an email address doesn't exist, should tell the user when they submit the reset form
- I don't think we need a new confirmation page, a notification back on the home/login page should be good

2020-01-08 23:39 UTC, dheniges commented on web/src/server/views/user/password-reset.ejs
> +          <input type="submit" class="button" value="reset your password">
Should capitalize "Reset"

2020-01-09 00:32 UTC, jjidt commented
Not sure about the first one, is that a security vulnerability to allow other users to see which email addresses are registered?  Updated the second with a flash message and fixed the button

2020-01-09 16:05 UTC, dheniges requested changes
Thanks for the updates. I think you're right about the security issue, we probably shouldn't reveal whether the account exists. Still seeing:
- No flash message. Not sure if it's not plumbed on that login page, but the message doesn't show up
- Should catch the error if an email is entered without a corresponding user. We want to try to keep the uncaught errors solely to cases we're not expecting. I think a 204 response is fine in this case, so there's no difference between an existing or non-existing user.

2020-01-09 19:46 UTC, jjidt commented
@dheniges check out the logging I added and see if you think that's a good way to structure it, I'm still seeing the flash message, so we might have to screenshare to see what's going on for you

2020-01-09 22:02 UTC, dheniges approved these changes
:+1: I SEE GÜD

2020-01-09 22:03 UTC, merged