Production Chunks
portway/portway pull request #42
Opened 2019-03-15 02:49 UTC by jcontonio

* Adds an AsyncComponent to dynamically import components, which are automatically chunked in webpack
* Splits vendor files more, and explicitly tells what files we need for vendor bundles in both dev and prod
* Adds gzip compression of static assets and minifying using terser in production build
* Adds BundleAnalyzerPlugin to analyze the bundles. Report is generated on `npm run build` and is placed in web/webpack-report.html
* Reduces bundles a ton

2019-03-15 18:03 UTC, dheniges commented
The compression, minification and whatnot all looks good.

I'm not sure about the bundle analyzer being part of the production build. It looks like the tool offers a CLI, so if we explicitly want the report we can generate it with that, without including it in the production build.

With the current setup, this report will get generated during the build process and hang out in the docker image that gets launched to prod. We can add a step to remove the file, but I'd rather just not generate it during a production build.

2019-03-15 21:16 UTC, jcontonio commented
Added gzip of static assets in production - I don't know how to test this

2019-03-15 23:10 UTC, dheniges requested changes
Update on doc, and then a question on vendor splitting

2019-03-15 23:10 UTC, dheniges commented on web/config/webpack.shared.js
> +          test: /[\\/]node_modules[\\/](bulma|react|react-dom|react-select|react-redux|react-router-dom|react-stripe-elements|redux|redux-thunk)[\\/]/,
this needs react-loadable too now. We'll soon want a better solution for building this vendor bundle. Won't webpack chunking on its own break up a larger bundle into chunks without specifying vendor given an entrypoint? Or are there optimizations from explicitly separating them?

2019-03-15 23:10 UTC, dheniges commented on docs/Web.md
> +For a report on bundle size, run `npm run build` in /web and check `webpack-report.html`.
this comment is outdated

2019-03-18 22:09 UTC, dheniges requested changes
Two things, I can update them if you want.

Also, the production build does not work with webpack/express. We'll have to debug more and I don't know how to test it without an integration test. The _build_ will work, but after logging in there's a blank page with no console errors. It's definitely missing some bundles or something.

2019-03-18 22:09 UTC, dheniges commented on docs/Web.md
> +* We are gzipping / minifying / and splitting code using react-loader
react-loader is removed now, right?

2019-03-18 22:09 UTC, dheniges commented on web/package.json
> +  "eslintIgnore": [
Can this not go in the `.eslintrc` file?

2019-03-18 22:24 UTC, dheniges commented on web/package.json
> +  "eslintIgnore": [
from eslint docs:
> ESLint always ignores files in /node_modules/*

So I'm just going to remove

2019-03-18 22:25 UTC, dheniges approved these changes

2019-03-18 22:50 UTC, merged