Replacing EasyMDE with regular CodeMirror
portway/portway pull request #437
Opened 2020-01-22 23:13 UTC by jcontonio

* Adds latest CodeMirror
* Should behave exactly as it did before, minus background colors on code
* Adds syntax highlighting for html, javascript, css, etc

We can add background colors later with our own custom AddOn

2020-01-22 23:15 UTC, jcontonio commented
PS. Make sure you test the Format menu

2020-01-23 21:30 UTC, jjidt requested changes
A few things:

<img width="440" alt="Screen Shot 2020-01-23 at 1 18 24 PM" src="https://user-images.githubusercontent.com/7355492/73025096-d0e8a700-3de3-11ea-99a4-44b882b07a68.png">

The cursor is expanding to all lines on line wrap

Format menu issues:

- Adding Bold element initially adds a horizontal rule
- Link and horizontal rule items don't add element or close menu
- Ordered list and Unordered list are reversed

2020-01-23 21:30 UTC, jjidt commented on web/src/client/js/components/FieldText/FieldTextComponent.js
> +// import 'codemirror/mode/markdown/markdown'
wanna leave these commented out lines?

2020-01-23 21:30 UTC, jjidt commented on web/src/client/js/components/FieldText/FieldTextComponent.js
> +  const editorRef = useRef()
nice

2020-01-24 00:37 UTC, jjidt approved these changes
👍 nice

2020-01-24 01:09 UTC, merged