Adjusting currentResource - Stops re-rendering of Header
portway/portway pull request #45
Opened 2019-03-18 22:53 UTC by jcontonio

2019-03-19 18:59 UTC, dheniges requested changes
A few small changes, and see my suggestion (I tested it locally, it works).

I don't love the reliance on the history object because it's mutable and there are no guarantees the component will update when it's mutated, or update how you'd expect it to. But it seems to work 🤷‍♀️

**Update**
After further testing, the location object exposed by react router is immutable, so we should replace reading the pathname with `location.pathname` to avoid future state bugs

2019-03-19 18:59 UTC, dheniges commented on web/src/client/js/components/Project/ProjectContainer.js
> +// import dataMapper from '../../libs/dataMapper'
hashtag deleteme

2019-03-19 18:59 UTC, dheniges commented on web/src/client/js/components/Header/Header.js
> +  history: PropTypes.object
history is no longer a used props on this component

2019-03-19 18:59 UTC, dheniges commented on web/src/client/js/libs/currentResource.js
> +    getLoadingStatusFromState: () => {},
```suggestion
    getLoadingStatusFromState: () => false,
```
The current implementation has a bug where once the resource is set, if it moves to an undefined resource the previous resource will never be unset. Returning false here tells useDataService the resource is loaded and will then set the appropriate (undefined in this case) data and the component using the hook will update accordingly

2019-03-19 21:31 UTC, jcontonio commented on web/src/client/js/libs/currentResource.js
> +    getLoadingStatusFromState: () => {},
Nice

2019-03-20 14:49 UTC, dheniges requested changes
Navigator's still pulling history, otherwise looks good

2019-03-20 14:49 UTC, dheniges commented on web/src/client/js/components/Navigator/NavigatorContainer.js
> +    currentResource('project', history.location.pathname), [history.location.pathname]
still have some history action going on here

2019-03-20 16:43 UTC, dheniges approved these changes

2019-03-20 16:44 UTC, merged