Org deletion job setup
portway/portway pull request #469
Opened 2020-01-30 23:35 UTC by jjidt

- sets up endpoints for canceled org deletion
- moves admin auth to header `Authorization: Admin <adminsecret>`
- sets up kubernetes cronjob

2020-02-03 18:14 UTC, dheniges requested changes
Feedback on the kube config

2020-02-03 18:14 UTC, dheniges commented on kubernetes/jobs/configMaps.yaml
> +    delete.api_url: 'https://api.portway.app'
I would re-use the existing config map that already has this url. I think it's in the web config map, which arguably should be renamed/moved into its own config map, but I wouldn't worry about that for now. So you can drop the changes to this file

2020-02-03 18:14 UTC, dheniges commented on kubernetes/jobs/deletedOrgCleanup.yaml
> +                  key: admin_api_key
We already have the admin key used in a secret, which you can see in the api deployment. Re-use that secret here. (note you can keep the `ADMIN_API_KEY` env var name and define it as the `admin_secret_key`)

2020-02-03 18:14 UTC, dheniges commented on kubernetes/jobs/deletedOrgCleanup.yaml
> +                  key: delete.api_url
this is where you can change the definition to pickup the web config map's public api url key

2020-02-03 18:14 UTC, dheniges commented on kubernetes/jobs/deletedOrgCleanup.yaml
> +            - name: LOG_ID
doesn't look like LOG_ID is used in the job, you can delete this env var

2020-02-04 01:44 UTC, jjidt commented
updated

2020-02-10 16:14 UTC, dheniges approved these changes
Gets canceled orgs, can't delete canceled ones less than 30 days old, or non-canceled orgs  👍

2020-02-11 18:15 UTC, merged