Projects List
portway/portway pull request #47
Opened 2019-03-19 21:27 UTC by jcontonio

Styles projects list according to Sketch file

* Adds animate option for turning animating on and off

2019-03-19 23:32 UTC, dheniges requested changes
I think you can drop refs in one case here, otherwise looks sweet

2019-03-19 23:32 UTC, dheniges commented on web/src/client/js/components/ProjectsList/ProjectListComponent.js
> +    setActiveProjectId(itemRef.current.getAttribute('data-projectid'))
instead of passing the ref and needing to read from the DOM to get the id, can't `ProjectsListItem` pass the project id to this function instead of the ref?

2019-03-20 00:54 UTC, jcontonio commented on web/src/client/js/components/ProjectsList/ProjectListComponent.js
> +    setActiveProjectId(itemRef.current.getAttribute('data-projectid'))
Nice catch, thanks!

2019-03-20 14:52 UTC, dheniges submitted a review, later dismissed

2019-03-20 16:51 UTC, dheniges approved these changes
It still builds

2019-03-20 16:53 UTC, merged