org api
portway/portway pull request #54
Opened 2019-03-25 23:57 UTC by jjidt

Adds a handful of things for signing up a new org/user

- organization BusinessTime :tm:
- custom password reset JWT auth with an a separate secret and a resetKey stored on the user (for initial password setting and reset in the future)
- hooks up sign-up views that rely on the token in the registration url(so we can easily switch this over to use an email for setting initial password)
- backfills some tests

2019-03-26 15:37 UTC, dheniges requested changes
Reviewed the codes and tests 👍 
- There's a failing test on codefresh, but locally they pass for me. Doing a rebuild to see what's up
- I'm not sure how the registration flow is supposed to work

2019-03-26 15:37 UTC, dheniges commented on api/src/businesstime/organization.test-i.js
> +    describe('when the target document is found', () => {
I changed this in my PR in another file, but I notice you have the text in these tests all referring to "document"

2019-03-26 15:37 UTC, dheniges commented on web/src/server/controllers/sign-up.js
> +  router.post('/registration', auth.jwtMiddleware, registerOrganization)
How is this auth flow supposed to work? I don't have a token at this point when I'm trying to register, so this endpoint will 401 me

2019-03-26 15:43 UTC, dheniges commented
Update on the tests: definitely getting intermittent failures on Codefresh and locally, although locally they seem to pass more often than not. It seems like a potential race condition where the cleanup is deleting records before the test finishes maybe?

2019-03-26 16:00 UTC, jjidt commented on web/src/server/controllers/sign-up.js
> +  router.post('/registration', auth.jwtMiddleware, registerOrganization)
That's not supposed to be an auth'd endpoint, I must have had a token and forgot to pull that out

2019-03-27 00:02 UTC, dheniges approved these changes

2019-03-27 00:15 UTC, merged