First-time experience UI
portway/portway pull request #562
Opened 2020-03-03 23:50 UTC by jcontonio

* Adds a new Dashboard component that contains a special project, and the projects list
* Fixes a bug in the Form disable logic

2020-03-04 17:22 UTC, dheniges requested changes
There are definitely a few edge case scenarios where the special project doesn't get styled. Testing I ran into through another path too but I couldn't figure out the steps to repeat it. Probably another alternate org loading path.

Everything else seems to work with this that I tested.

Last thing is styling on the projects list now, I feel like it needs some divider so it's clear which user icons are associated with the project:
<img width="919" alt="Screen Shot 2020-03-04 at 8 55 12 AM" src="https://user-images.githubusercontent.com/2146425/75905369-9538f800-5df9-11ea-8fd2-7b0da866318a.png">

2020-03-04 17:22 UTC, dheniges commented on web/src/client/js/actions/organization.js
> +    const results = await Promise.all([fetch(`v1/organizations/${orgId}`), fetch(`v1/organizations/${orgId}/introProjectId`)])
It seems like this action isn't hit if you go to the admin page for an organization. I wound up with the intro project not getting the special styling:
1. Go to the organization admin page
1. Change a setting on the organization (I checked "Everyone can create projects")
1. Click the Portway logo to go back to the dashboard. The intro project is not styled.

2020-03-04 20:15 UTC, jcontonio commented
Fixed up, and have a surprise for you :dirk:

2020-03-04 22:12 UTC, dheniges commented
@jcontonio doesn't look like you pushed up any changes?

2020-03-04 22:44 UTC, jcontonio commented
Pushed

2020-03-04 23:55 UTC, dheniges requested changes
A couple other comments, and there's a lot of whitespace at larger screen sizes, I think it needs to be tightened up or dividers added or something. The project users and icons are kinda floating in the abyss. The hover effect helps offset this when you actually interact with it, but see the screenshot:
<img width="1659" alt="Screen Shot 2020-03-04 at 3 51 30 PM" src="https://user-images.githubusercontent.com/2146425/75934096-7dc93180-5e30-11ea-9c45-83e2ed9829f2.png">

2020-03-04 23:55 UTC, dheniges commented on web/src/client/js/components/Dashboard/DashboardSpecialProject.js
> +const lsShowMessage = localStorage.getItem('sp-message')
What do you think about adding a date check to this? Like if the project was created > 30 days ago, never show the message?

2020-03-04 23:55 UTC, dheniges commented on web/src/client/js/components/Dashboard/DashboardSpecialProject.js
> +  const assignedProject = project.accessLevel == null
I'm not following this logic. A project can have a default accessLevel independent of users being individually assigned to the project

2020-03-05 18:06 UTC, jcontonio commented on web/src/client/js/components/Dashboard/DashboardSpecialProject.js
> +  const assignedProject = project.accessLevel == null
We don't show the ProjectUsers list if the project has an accessLevel set, because it is accessible to everyone. That's when we show the "Unlocked". I think I just have a very terrible variable name

2020-03-05 18:08 UTC, dheniges commented on web/src/client/js/components/Dashboard/DashboardSpecialProject.js
> +  const assignedProject = project.accessLevel == null
ah gotchya, maybe just call it `showProjectUsers` ?

2020-03-05 22:04 UTC, jcontonio commented
Changed ProjectList to use the sortable Table component, and rendering the special project as the first item in that table if it exists

This is prepping for sortable / filterable projects

2020-03-06 19:58 UTC, dheniges approved these changes
Looks great 👍

2020-03-06 20:31 UTC, merged