sync string and number fields
portway/portway pull request #563
Opened 2020-03-03 23:57 UTC by jjidt

also adds number length limit

2020-03-04 16:25 UTC, dheniges requested changes
It works in the update scenario, but some issues I came across. The 2nd and 3rd issues may be separate from this PR, in which case they can go in Asana.

- Two react warnings, see screenshots below
- When user 1 adds a new string or number, user 2 doesn't see it until user 1 enters a value
- Reordering fields isn't reflected for other users until refresh

<img width="1122" alt="Screen Shot 2020-03-04 at 8 20 06 AM" src="https://user-images.githubusercontent.com/2146425/75900334-9ebe6200-5df1-11ea-8ad7-c0df09ef6216.png">
<img width="1369" alt="Screen Shot 2020-03-04 at 8 20 31 AM" src="https://user-images.githubusercontent.com/2146425/75900347-a251e900-5df1-11ea-926e-b4dc75bd4fb3.png">

2020-03-04 16:25 UTC, dheniges commented on sync/src/app.js
> -
It's a good change, it's a good change.
https://www.youtube.com/watch?v=Rt3gcSyL5vg

2020-03-05 00:01 UTC, jjidt commented
It made sense to go ahead and fix sync for create/remove/reorder, check it :shockandawe:

2020-03-05 00:43 UTC, dheniges approved these changes
What can I say? It syncs :tada: :realjj:

2020-03-05 00:44 UTC, merged