Rate limit notifications
portway/portway pull request #616
Opened 2020-03-31 20:30 UTC by jcontonio

* Adds rate limit notifications
* Reduces the amount of notifications to 1 per error code
* Fixes a few rendering issues in components that weren't checking for things first

2020-04-03 17:20 UTC, dheniges requested changes
Everything looks good except those console logs 👀

2020-04-03 17:20 UTC, dheniges commented on web/src/client/js/components/Notifications/NotificationList.js
> +  console.log(notifications)
👀

2020-04-03 17:20 UTC, dheniges commented on web/src/client/js/components/Notifications/NotificationList.js
> +  console.log(trimmedNotificationsList)
:eyes:

2020-04-03 17:27 UTC, jcontonio commented
Whoooooooops

2020-04-06 16:41 UTC, dheniges approved these changes
👍

2020-04-06 16:46 UTC, merged