file field
portway/portway pull request #618
Opened 2020-04-01 20:33 UTC by jjidt

sets up file field, still needs styling

2020-04-02 19:54 UTC, dheniges requested changes
Just one change in the client that I stumbled across the other day, then this looks good to go. I'm ignoring all the copypasta for image field -> file field on the client :)

2020-04-02 19:54 UTC, dheniges commented on web/src/client/js/components/DocumentFields/DocumentFieldComponent.js
> +  const dataField = field.type !== FIELD_TYPES.TEXT && field.type !== FIELD_TYPES.IMAGE && field.type !== FIELD_TYPES.FILE
this should be a whitelist

2020-04-03 16:01 UTC, jcontonio commented on web/src/client/js/components/DocumentFields/DocumentFieldComponent.js
> +  const dataField = field.type !== FIELD_TYPES.TEXT && field.type !== FIELD_TYPES.IMAGE && field.type !== FIELD_TYPES.FILE
All set

2020-04-03 17:47 UTC, dheniges approved these changes
:+1:

2020-04-03 17:54 UTC, merged