Log out user
portway/portway pull request #62
Opened 2019-03-28 18:56 UTC by jcontonio

* Adds logout route, action, and reducer (in case we want to do anything in the future)
* Deletes token cookie
* Redirects to / using location.href from the reducer

2019-03-28 19:03 UTC, jcontonio commented
I forgot, this also fixes buttons

2019-03-28 23:21 UTC, dheniges requested changes
It's completely functional, but I think the logic for logout should live in an action, not the store

2019-03-28 23:21 UTC, dheniges commented on web/src/client/js/components/Logout/LogoutComponent.js
> +  Store.dispatch(Users.logout())
I think this is a nice spot for the `useEffect` hook with an empty dependency array so it only runs on mount. We only ever want this dispatch to occur once if this component is in the render path.

I like having the logout action, but I think the redirect logic and cookie setting should live in an action. So we'd dispatch a 'logout' action that dispatches to the store, sets the cookie and then does the redirect. It'd be similar to an action that fetches data from the API.

2019-03-28 23:21 UTC, dheniges commented on web/src/client/js/reducers/users.js
> +      location.href = '/'
I think the store reducers should only ever respond to an action and data in the action to change state. See my comment on wrapping it in an action function

2019-03-29 00:09 UTC, dheniges approved these changes

2019-03-29 00:09 UTC, merged