New: Splitting text fields for new fields
portway/portway pull request #620
Opened 2020-04-01 23:06 UTC by jcontonio

Updated to do all the API work in one action. Works nicely!

1. Have a big markdown body of text
2. Put your cursor anywhere in it
3. Add a new field

This is going to split the body of the text at your cursor / line position, create your new field, create a new text field with the text after the cursor position, and then reorder the two new fields to put them in the right spot. 

There are 5 unnecessary renders, but that's in `release` too

2020-04-06 23:59 UTC, jjidt submitted a review, later dismissed
I like this, makes sense to be able to insert other fields 

A couple things:

- When a new field is created(non split), the cursor no longer goes to that field
- There's a scroll position jump when the new split field is inserted, which can be a tiny bit disorienting

2020-04-06 23:59 UTC, jjidt commented on web/src/client/js/actions/field.js
> +export const createNewFieldWithTheSplitOfThePreviousFieldAndReOrderThemAppropriately = (
😆 what a name!

2020-04-07 19:38 UTC, jcontonio commented
Update: Switched tracking of lastCreatedFieldId and instead of manually adjusting the CodeMirror instance, calling update endpoint on that field so we get no delay or re-render. Problem is right now calling fetchDocument() doesn't re-render the CodeMirror instance with its new, split value.

Waiting on feature-sync to get in there to see if that'll make things easier. 

Need to call `removeLastCreatedFieldId` from the onFocus handler of `DocumentFieldComponent` once feature-sync is in there.

2020-04-16 20:59 UTC, jcontonio commented on web/src/client/js/actions/field.js
> +export const createNewFieldWithTheSplitOfThePreviousFieldAndReOrderThemAppropriately = (
Solved scroll thing

2020-04-17 22:37 UTC, dheniges requested changes
A few code things, but the actual splitting itself seems very nice

2020-04-17 22:37 UTC, dheniges commented on web/src/client/js/actions/index.js
> +  removeLastCreatedFieldId: makeActionCreator(ActionTypes.REMOVE_LAST_CREATED_FIELD_ID, 'fieldId'),
I don't see this action used anywhere?

2020-04-17 22:37 UTC, dheniges commented on web/src/client/js/actions/field.js
> +export const removeLastCreatedFieldId = (fieldId) => {
Same thing, I don't see this called anywhere

2020-04-17 22:37 UTC, dheniges commented on web/src/client/js/components/DocumentFields/DocumentFieldsContainer.js
> +  }, [])
this should at least have `documentReadOnlyMode` as a dependency, and fields, since those can change. Otherwise this creates a reference to fields on the first render and the "getNewNameInSequence" will keep returning the same name.

2020-04-17 22:44 UTC, jcontonio commented on web/src/client/js/actions/index.js
> +  removeLastCreatedFieldId: makeActionCreator(ActionTypes.REMOVE_LAST_CREATED_FIELD_ID, 'fieldId'),
There was a place we were going to call this... @jjidt do you remember? I know we were waiting until after sync got in.

2020-04-17 22:59 UTC, jjidt commented on web/src/client/js/actions/index.js
> +  removeLastCreatedFieldId: makeActionCreator(ActionTypes.REMOVE_LAST_CREATED_FIELD_ID, 'fieldId'),
I really can't remember what the deal was with that, where is that last created field id state getting updated now? seems like it's working how we want

2020-04-20 16:46 UTC, dheniges approved these changes
woooo

2020-04-20 16:48 UTC, merged