Updates: Dims out fields that are being edited by someone else
portway/portway pull request #637
Opened 2020-04-16 18:11 UTC by jcontonio

Grays them out and disables any mouse interaction

2020-04-17 19:31 UTC, dheniges requested changes
This disables all field types, including text fields. I don't think we want that?

2020-04-17 19:46 UTC, jcontonio commented
Oh duh

2020-04-17 19:50 UTC, jcontonio commented
Updated

2020-04-17 21:01 UTC, dheniges requested changes
Works good now, looks like just a leftover constant whitelist you started?

2020-04-17 21:01 UTC, dheniges commented on web/src/client/js/components/DocumentFields/DocumentFieldComponent.js
> +const FIELDS_THAT_DISABLE_WHEN_EDITING = [
don't need this now?

2020-04-20 16:50 UTC, dheniges approved these changes
:sealeel:

2020-04-20 17:04 UTC, merged