fix field name flash
portway/portway pull request #655
Opened 2020-04-24 18:58 UTC by jjidt

- adds a nifty usePrevious hook that will return the previous value on each re-render
- adds a check for generic name changes and image name changes, if the incoming field.name is the same as the previous one, we know not to update the current.value

2020-04-24 22:19 UTC, dheniges requested changes
I'm still getting the flash on this, it seems like there's a point where the previousValue matches the field name in redux here after a render but before the PUT response is received

2020-04-25 00:33 UTC, jjidt commented
added an isUpdating check there as well and it seems to behave better when wildly clicking around and updating things. This probably won't completely solve it for super slow connections, so we might want to implement some kind of component update date vs. lastUpdatedAt date check in the future, possibly?

2020-04-27 17:55 UTC, dheniges reviewed
I think the isUpdating check fixes the issue. I removed the previousField code and it still works as expected, so I don't think we want/need that previousField check here?

2020-04-27 18:00 UTC, dheniges requested changes
This fixes my flashing problems. I think it needs one dependency update in the useEffect though

2020-04-27 18:00 UTC, dheniges commented on web/src/client/js/components/DocumentFields/DocumentFieldComponent.js
> +  }, [field, isUpdating])
I think this needs previousField as a dependency

2020-04-27 18:16 UTC, jjidt commented
updated

2020-04-27 18:22 UTC, dheniges approved these changes
:realjj:

2020-04-27 18:27 UTC, merged