Adding terms of service checkbox
portway/portway pull request #681
Opened 2020-05-07 18:25 UTC by jcontonio

Adds checkbox to sign-up entrypoint

2020-05-07 20:55 UTC, dheniges requested changes
Probably worth adding the terms url to the constants so it's in one spot

2020-05-08 16:29 UTC, jcontonio commented
Updated

2020-05-08 18:15 UTC, dheniges approved these changes

2020-05-08 18:21 UTC, dheniges approved these changes

2020-05-08 18:34 UTC, merged