field endpoints
portway/portway pull request #70
Opened 2019-04-05 22:39 UTC by jjidt

- document/field endpoints
- field instance methods for value setting/getting
- monitored database to ensure values were getting cascade deletion on field deletion

2019-04-06 00:22 UTC, dheniges requested changes
JJ you've created a masterpiece. This is much more straightforward than I was anticipating, thanks to those pesky relationships seeming to do their job.

Looks like an unnecessary arg on a getter, otherwise it's solid

2019-04-06 00:22 UTC, dheniges commented on api/src/controllers/documentFields.js
> +  body.orgId = orgId
I recall this code somewhere else, eventually that should probably be an error message if they pass an invalid org id? This works for now though.

2019-04-06 00:22 UTC, dheniges commented on api/src/db/__testSetup__/initializeTestDb.js
> +    return model.destroy({ truncate: true, cascade: true })
What does this do that truncate() wasn't?

2019-04-06 00:22 UTC, dheniges commented on api/src/db/models/field.js
> +    return this[`get${modelName}`](fieldValue)
isn't `fieldValue` here and two lines above always going to be undefined since this is a getter?

2019-04-06 00:25 UTC, jjidt commented on api/src/db/__testSetup__/initializeTestDb.js
> +    return model.destroy({ truncate: true, cascade: true })
after defining the value/field relationship with the cascading delete, it started to throw an error message on truncate, this fixed it

2019-04-06 00:26 UTC, jjidt commented on api/src/db/models/field.js
> +    return this[`get${modelName}`](fieldValue)
oops, yeah copypasta

2019-04-06 00:26 UTC, jjidt commented on api/src/controllers/documentFields.js
> +  body.orgId = orgId
yeah, we're doing this elsewhere, we could probably tackle all those in a PR

2019-04-08 14:59 UTC, dheniges approved these changes

2019-04-08 16:01 UTC, merged