project export coordinator
portway/portway pull request #728
Opened 2020-07-07 21:41 UTC by jjidt

write md files, download assets, and zip it up

TODO:

- .env temp file path
- controller perms
- worker/upload to s3

2020-07-08 17:21 UTC, dheniges requested changes
One code question (see comment), and then:
- if I have a date field, with or without a value, I get an error: cannot read property `toISOString` of null
- A project with 1 document with a single text field just hangs when I try to export it.

I'm running the export through postman

2020-07-08 17:21 UTC, dheniges commented on api/src/integrators/zip.js
> +  return Array.prototype.concat(...files)
This is returning a new array of the files, which are arrays or strings it looks like. But why the new array vs returning `files` here?

2020-07-09 00:08 UTC, jjidt commented on api/src/integrators/zip.js
> +  return Array.prototype.concat(...files)
just a shortcut to flatten a multi dimensional array, which files ends up being

2020-07-20 15:32 UTC, dheniges commented
This work is now in the feature branch via another PR, closing

2020-07-20 15:32 UTC, closed without merging