webhook delivery
portway/portway pull request #764
Opened 2020-09-16 22:26 UTC by dheniges

Delivers webhooks

2020-09-18 22:09 UTC, jjidt requested changes
couple commented out things and one question, tested it out with ngrok and a small express server and it delivered my webhooks :tada:

2020-09-18 22:09 UTC, jjidt commented on api/src/businesstime/webhook.js
> +// import { getPaginationOptions, getSortOptions } from '../libs/queryFilters'
leave ?

2020-09-18 22:09 UTC, jjidt commented on api/src/controllers/projectWebhooks.js
> +// import BusinessOrganization from '../businesstime/organization'
need this?

2020-09-18 22:09 UTC, jjidt commented on api/src/db/models/webhookdelivery.js
> +    resultCode: DataTypes.STRING
is there a reason to have this as a string instead of an integer?

2020-09-22 15:07 UTC, dheniges commented on api/src/db/models/webhookdelivery.js
> +    resultCode: DataTypes.STRING
in my head I wasn't sure if we'd have non-http response codes/strings, but maybe all webhooks will be http? None of the code currently cares whether it's a number or string. What do you think?

2020-09-22 18:12 UTC, jjidt approved these changes

2020-09-24 16:55 UTC, merged