linting
portway/portway pull request #8
Opened 2019-02-07 00:14 UTC by jjidt

2019-02-07 16:44 UTC, dheniges commented
From JJ: "looks like the editor is picking up some linting issues not found during commit, if you wanna take a look at those globs in the package.json lint-staged config for web and api, maybe I'm missing something"

2019-02-07 17:04 UTC, dheniges submitted a review, later dismissed
The husky precommit hook isn't triggering for me, so it's not running `eslint --fix`. Is there additional setup/config needed for that?

Also, starting/restarting the API is real slow with nodemon. I wouldn't expect the stripe dependencies to be massive. Not seeing anything obvious in babel-node, which could be a culprit

2019-02-07 17:04 UTC, dheniges commented on api/package.json
> +    "eslint": "^5.13.0",
should be a dev dependency?

2019-02-07 17:18 UTC, dheniges commented on web/package.json
> +      "*.{js,jsx,css,md}": [
this should use the same pattern dir match as the api: `"src/**/*.{js,jsx...}"` but with css and whatnot

2019-02-07 18:53 UTC, dheniges submitted a review, later dismissed
I updated the package config for lint-staged to use relative paths to the package.json file. lint-staged is a pretty nice lib in that it has a debug tool built-in to the binary: https://github.com/okonet/lint-staged#command-line-flags

Two remaining issues:

1. On web there are conflicting rules between prettier and eslint about parens around a single argument in a function. Running eslint --fix will switch back and forth between adding or removing parens.

2. There's an empty .eslintrc file in the root of the repo that should be removed

2019-02-07 21:22 UTC, jjidt commented
@dheniges check it again, I tested with a bunch of files and it seems to be catching things correctly now

runs prettier via pretty-quick on staged files before linting, so bypasses the arrow paren nonsense

2019-02-07 21:45 UTC, dheniges requested changes
The eslint/prettier weirdness seems resolved!

But, API changes are not getting detected based on the rule. It works in web with the same rule which makes no sense

The config I added earlier fixed this for me:
```
    "linters": {
      "src/**/*.{js,json}": [
        "eslint --fix",
        "git add"
      ]
    },
    "relative": true
```

Lint debug run with the above settings:
<img width="500" alt="screen shot 2019-02-07 at 1 46 47 pm" src="https://user-images.githubusercontent.com/2146425/52445042-d9ff3c00-2ade-11e9-9483-cc1b407227f3.png">

2019-02-07 21:45 UTC, dheniges commented on api/package.json
> +      "*.{js}": [
this rule is not picking up changed files for me in the server.

<img width="675" alt="screen shot 2019-02-07 at 1 39 31 pm" src="https://user-images.githubusercontent.com/2146425/52444658-d919da80-2add-11e9-92ea-9be16f3455c3.png">

That relative path I added before fixed this. For reasons I don't understand at all, that config works in web, but I like the explicit relative path config so the web linter can never pick up changed API files.

Weird web config below that's working:
<img width="838" alt="screen shot 2019-02-07 at 1 41 48 pm" src="https://user-images.githubusercontent.com/2146425/52444789-36159080-2ade-11e9-9354-27fad54f49f0.png">

2019-02-07 22:43 UTC, jjidt commented
using 'relative' flag on api settings is resulting in this for me when I change a file and try to commit

```fatal: pathspec 'src/coordinators/billing.js' did not match any files
husky > pre-commit hook failed (add --no-verify to bypass)

2019-02-08 01:13 UTC, dheniges approved these changes

2019-02-08 01:14 UTC, dheniges commented
For posterity:

For reasons unknown the lint-stage config in api/package.json is not triggering the linting on the post-commit hook for me. Exact same config works fine in web 🤷‍♀️

2019-02-08 01:20 UTC, merged