add renderedValue to fields
portway/portway pull request #890
Opened 2021-03-16 20:31 UTC by jjidt

- just dumb ejs templates for now, can hand this off to Jay to expand on those
- there's a todo in there for passing along the image alt, width, and height when those are available

2021-03-22 17:15 UTC, jcontonio commented
Here's what I'm thinking for each of the templates:

1. Add `type`, `name`, and `value` to all the fields, and use this as the generic template for everything. This way someone can style Portway divs specifically, and then style field types individually

```ejs
<div data-source="portway" data-type="<%= type %>" data-name="<%= name %>">
	{{ value }}
</div>
```

2. For the File template, add `download` attribute:

```ejs
<div data-source="portway" data-type="<%= type %>" data-name="<%= name %>">
	<a href="<%= value %>" download><%= name %></a>
</div>
```

3. For the Date template, use the `time` [tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time). Let the debate begin on the format here:

```ejs
<div data-source="portway" data-type="<%= type %>" data-name="<%= name %>">
	<time datetime="<%= value %>"><%= formattedDate? %></time>
</div>
```

4. For the Image template, we'll want to add the srcset, and add an alignment attribute:

```ejs
<div data-source="portway" data-type="<%= type %>" data-name="<%= name %>" data-align="<%= alignment %>">
	<img
		src="<%= webpSource.half %>"
		srcSet="<%= webpSource.half %>, <%= webpSource.full %> 2x"
		alt="<%= alt %>"
		width="<%= width %>"
		height="<%= height %>"
		align="<%= alignment %>"
	/>
</div>
```

2021-03-23 16:37 UTC, jjidt commented
need to update renderedValue when image conversion job is done

2021-03-25 00:23 UTC, jjidt commented
- updated with a publishing fix (all fields get copied over for a published field, rather than cherry picking like we were before), so publishing reliability should be verified for all field types
- plugged in new templates, not sure if we want all the escaping that is happening, also image fields will briefly have empty srcSet values until the worker is done processing, not sure if that will have side effects

2021-03-30 19:05 UTC, jcontonio commented
@jjidt whenever you're done with duplicate let's remove whatever escaping is going on here, then we're good

2021-04-08 17:04 UTC, dheniges requested changes
Some changes to make, but it worked for me 👍 

Let me know if I'm missing something on the renderedValue being computed in the Business layer.

2021-04-08 17:04 UTC, dheniges commented on api/src/coordinators/markdown.js
> +const md = new MarkdownIt({ breaks: true })
This seems like it would impact the structured value output if it's sticking `br`s on all newlines, but the tests still pass so maybe it's not?

2021-04-08 17:04 UTC, dheniges commented on api/src/coordinators/documentVersion.js
> +  delete fieldForUpdate.documentId
`documentId` doesn't change here does it?

2021-04-08 17:04 UTC, dheniges commented on api/src/coordinators/documentVersion.js
> +  return fieldForUpdate
This is going from a whitelist to a blacklist of fields, but still has to deal with the individual case of the structuredValue. Guess it's a tradeoff between forgetting to update this function with new fields but still having them in the API, vs. exposing internals we didn't mean to. :shrug:

2021-04-08 17:04 UTC, dheniges commented on api/src/businesstime/field.js
> +    await createdField.update({ renderedValue })
Doesn't this make more sense in the field coordinator? It would save a database hit (createdField created, then subsequently updated here for the renderedValue)

2021-04-08 17:04 UTC, dheniges commented on api/src/businesstime/field.js
> +    await updatedField.update({ renderedValue })
Same comment, I could be missing something but this seems like a coordinator action

2021-04-08 17:04 UTC, dheniges commented on api/src/libs/fieldRenderedValue/index.js
> +export function getRenderedValueByType(field, value) {
Seems like throwing a few tests here for different field types is worth the time. I also think a warning log if the input field type isn't found might save us a future headache if we forget to update this with a new field type in the future.

2021-04-08 17:22 UTC, jjidt commented on api/src/coordinators/markdown.js
> +const md = new MarkdownIt({ breaks: true })
I think I checked and the structured value was already doing this by default, we can double check though

2021-04-08 17:30 UTC, dheniges commented on api/src/coordinators/markdown.js
> +const md = new MarkdownIt({ breaks: true })
peeked at the tests and they definitely cover it, so we're good

2021-04-08 17:35 UTC, jjidt commented on api/src/coordinators/documentVersion.js
> +  return fieldForUpdate
yeah, if you have a suggestion for a way you'd prefer I'm open to it, if it's a whitelist, then adding a field would require updating here, updating the incoming duplication code, and updating the public fields array, but maybe if they were all constants in the same file that would be easier to remember

2021-04-08 17:39 UTC, dheniges commented on api/src/coordinators/documentVersion.js
> +  return fieldForUpdate
I like the idea of defining it in constants, do you want to add that in asana?

2021-04-08 18:08 UTC, jjidt commented on api/src/coordinators/documentVersion.js
> +  delete fieldForUpdate.documentId
it doesn't, but we'll get an error if we try to pass that on the update

2021-04-08 18:10 UTC, jjidt commented on api/src/businesstime/field.js
> +    await createdField.update({ renderedValue })
I had that originally, but moved it here because we needed additional fields that weren't coming in on the body

https://github.com/BonkeyBong/portway/pull/890/commits/5ab542842cf752191a1baf27ec1e837d599cde05

2021-04-09 20:28 UTC, jjidt commented
updated, rendering is now happening in the coordinator, and lots of fancy new tests

2021-04-13 17:04 UTC, dheniges approved these changes

2021-04-13 17:17 UTC, merged