document duplicate
portway/portway pull request #896
Opened 2021-03-31 20:47 UTC by jjidt

- document duplicationz with tests
- after this is merged, we can convert the intro project coordinator to use the same field duplication

dupe endpoint is:

`/projects/:projectId/documents/:docId/duplicate`

 Next steps: update the documentation with new endpoint

2021-04-08 18:40 UTC, dheniges requested changes
It's close, a couple issues:
- Double image trouble
- Order preservation

2021-04-08 18:40 UTC, dheniges commented on api/src/businesstime/field.js
>    if (body.type === FIELD_TYPES.TEXT && body.value && !Boolean(body.structuredValue)) {
```suggestion
  // Added 2/24/2021 -DH
  if (body.type === FIELD_TYPES.TEXT && body.value && !Boolean(body.structuredValue)) {
```

2021-04-08 18:40 UTC, dheniges commented on api/src/coordinators/document.js
> +  // just in case, go through the normal pathway for fetching
:+1:

2021-04-08 18:40 UTC, dheniges commented on api/src/coordinators/field.js
> +    await fieldCoordinator.addImageFieldFromUrlToDocument(newParentDocId, body, body.value)
I think this needs to return, otherwise it creates two image fields

2021-04-08 18:40 UTC, dheniges commented on api/src/coordinators/document.js
> +  await Promise.all(fields.map((field) => {
this runs async, so order isn't preserved. I didn't trace it back, but I'm sure somewhere the `normalizeFieldOrder...` function or whatever it's called is getting called. Maybe in the image copy on field coordinator? Not sure

2021-04-09 23:02 UTC, jjidt commented
nice catches there, updated

2021-04-13 17:05 UTC, dheniges approved these changes

2021-04-13 17:19 UTC, merged